### ISSUE TITLE
`Getting started with Qiskit` doesn't work

### ISSUE THREAD

**Issue by takineko-tfs** [TheFlightSims/research-labs#10]
**Describe the bug**
On the home screen of Jupyter Lab, there's `Getting stared with Qiskit` button, but it leads to an Error, instead of open a notebook. 

**Expected behavior**
This button must open something, so it returns to nothing.

**Screenshots**

![Capture](https://github.com/TheFlightSims/research-labs/assets/115929530/472fce68-57b3-4d3e-ad63-6bc3915f760a)

**Recommendations**
 1. If the support for Qiskit and Quantum computing is the main feature of Research Labs, readdress the button to avail of notebook
 2. Perform the removal of this button, if the supporting Qiskit isn't the main feature.

**Comment by TheFlightSimsOfficial** [comment]
We're just committed the solution at [here](https://github.com/TheFlightSims/research-labs/commit/f58d30a4637ad0360853ad52fa739d596271372b)

If you wish to contribute to this project, you can review these.

All thanks.

**Comment by takineko-tfs** [comment]
Problem solved in #13
