### ISSUE TITLE
Missing theme on first launch

### ISSUE THREAD

**Issue by takineko-tfs** [TheFlightSims/research-labs#12]
**Describe the bug**
On the first launch/registration, the Jupyter Lab **seems** missing to open up the theme.

**To Reproduce**
The problem starts right after entering the Jupyter Lab (first launch). 

**Expected behavior**
`Quantum Lab system` theme must be the default and load first at all.

**Screenshot**

![Capture2](https://github.com/TheFlightSims/research-labs/assets/115929530/09879149-337e-490d-8919-c5ddbf469eee)

**Solving (temporary)**

I had chosen the Quantum Lab system to store the behavior of Jupyter Lab.

![Capture3](https://github.com/TheFlightSims/research-labs/assets/115929530/814052a8-f191-477a-93a1-5448209a068e)

**Comment by TheFlightSimsOfficial** [comment]
Thanks for your report.

We've just committed a fix for this issue at [here](https://github.com/TheFlightSims/research-labs/commit/4feb7e81ff976fc5b30976c1a68d22fa8f9aeb5f)

Hope you can sometimes to review the code, and let us know soon.

**Comment by takineko-tfs** [comment]
Problem solved.
