### ISSUE TITLE
Auto execution when opening the Python3 (ipykernel, the one with Qiskit icon) gets an error

### ISSUE THREAD

**Issue by takineko-tfs** [TheFlightSims/research-labs#13]
**Describe the bug**
Auto execution when opening the Python3 (ipykernel, the one with the Qiskit icon) gets an error:

The error `AccountNotFoundError: 'No default ibm_quantum account saved.'` results from the execution 

**To Reproduce**

After clicking this button, the notebook with the automatic execution:

![image](https://github.com/TheFlightSims/research-labs/assets/115929530/8211b2e4-8e7d-4f29-b92c-4de93b3b8b7f)

After that, the error happens.

![Capture4](https://github.com/TheFlightSims/research-labs/assets/115929530/53ba6667-aff8-4d7b-aae9-56499a3fab59)

**Expected behavior**
The code must be changed, or this should be removed.

**Comment by TheFlightSimsOfficial** [comment]
Thanks for your report. 

The problem started with JavaScript files. 

We are just committed the changes [here](https://github.com/TheFlightSims/research-labs/commit/2e9ed2e156fcdd5f3673df97a65038f846ca7508)

**Comment by takineko-tfs** [comment]
Problem solved. The Qiskit Notebook and Qiskit Console are no longer existed.
