### ISSUE TITLE
PIP Updates may result to conflict with IBM-Q packages

### ISSUE THREAD

**Issue by takineko-tfs** [TheFlightSims/research-labs#7]
**Describe the bug**
[`jupyrer_update_all.sh:13`](https://github.com/TheFlightSims/research-labs/blob/main/admin-scripts/jupyter_update_all.sh) uses `pip install` to update packages. 

It results in conflicts with the following IBM-Q packages:

 - `ibm_q_lab_server_extension`
 - `ibm_q_lab_ui_extensions`
 - `ibm_quantum_widgets`

**What do the conflicts cause?**

`ibm_q_lab_ui_extensions` and `ibm_quantum_widgets` are the only two codings providing advanced features for Research Labs (such as Quantum themes and Quantum Circuit Composer). It depends on Jupyter Lab 3.6.1 (which is outdated). 

Upgrading to the latest version, without using the virtual environment `env`, leads all package upgrades to its latest version without checking the misconfigurations with others.

**Recommendation actions**

Whenever the upgrade is completed, ensure that the administrator runs `pip check` to see and resolve all conflicts packages. 

However, based on my research, it may take 1-2 hours to do this, leading to more significant server maintenance problems.

**Comment by TheFlightSimsOfficial** [comment]
So far from now, `pip upgrade` will not be used. 

The user must use the command `pip install  -r ~/admin-scripts/pip_packages.txt` or using the pre-defined shell.

**Comment by takineko-tfs** [comment]
Problem solved.
