### ISSUE TITLE
`terminado` removal is not required

### ISSUE THREAD

**Issue by takineko-tfs** [TheFlightSims/research-labs#8]
In [`jupyter_setup_server.sh:195`](https://github.com/TheFlightSims/research-labs/blob/main/admin-scripts/jupyter_setup_server.sh) and [`jupyter_update_all.sh:17`](https://github.com/TheFlightSims/research-labs/blob/main/admin-scripts/jupyter_update_all.sh) contain the forced removal for `terminado` package.

This is not required in Research Labs since the [`page_config.json:17`](https://github.com/TheFlightSims/research-labs/blob/main/jupyter-ext-pkg/ibm-q-lab/local/etc/jupyter/labconfig/page_config.json)  defined access to the terminal for users is not available.

**More detail about this issue**

`terminado` is a Windows/Linux/macOS terminal simulator that provides back-end and front-end solutions for applications and services in Jupyter (including Lab, Hub, Server, and their extensions).

Without it, the conflicts between packages start and cannot resolve after the `terminado` is back.

**Disable `terminado` in a better way**

Because of the security issue, `terminado` on Jupyter Lab is configured in Enterprise environments, and Campus is disabled by default.

I also see the `terminado` for users is already disabled in [`page_config.json:17`](https://github.com/TheFlightSims/research-labs/blob/main/jupyter-ext-pkg/ibm-q-lab/local/etc/jupyter/labconfig/page_config.json)

**Comment by TheFlightSimsOfficial** [comment]
Just perform the changes in the source (view in [here](https://github.com/TheFlightSims/research-labs/commit/a0204005142259c4df39ff36fbc0fa58de51d035))

**Comment by takineko-tfs** [comment]
Problem solved.
