### ISSUE TITLE
MySQL password leaks

### ISSUE THREAD

**Issue by takineko-tfs** [TheFlightSims/research-labs#9]
**Describe the bug**

The MySQL password file [mysql_password.txt](https://github.com/TheFlightSims/research-labs/blob/main/admin-scripts/mysql_password.txt) locates in `/etc/jupyter` after the installation causes leaking of the MySQL root password.

This can be done by using Python3.10 kernel to bypass the disabling of `terminado` (mentioned in #8)

**Affected files**

 - [jupyter_setup_server.sh](https://github.com/TheFlightSims/research-labs/blob/main/admin-scripts/jupyter_setup_server.sh)
 - [mysql_change_password_manual.sh](https://github.com/TheFlightSims/research-labs/blob/main/admin-scripts/mysql_change_password_manual.sh)
 - [mysql_generate_random_password.sh](https://github.com/TheFlightSims/research-labs/blob/main/admin-scripts/mysql_generate_random_password.sh)
 - [mysql_password.txt](https://github.com/TheFlightSims/research-labs/blob/main/admin-scripts/mysql_password.txt)
 - [mysql_reset_password.sh](https://github.com/TheFlightSims/research-labs/blob/main/admin-scripts/mysql_reset_password.sh)

**To Reproduce**

The user can use Notebook or Console to execute the terminal. After that, the user can use the following code to read files in `/etc/jupyter`, including the `mysql_password.txt`:

```
from os import system as sys
sys('ls -l /etc/jupyter/')
sys('cat /etc/jupyter/mysql_password.txt')
```

**Expected behavior**

The system must block access to the folder `/etc/jupyter/` (means reading, writing, and execution) for all users except the `root` and `administrator`.

**Recommendation actions**

 1. Block users from executing the `os.system` terminal commands. There's no reason to do let users execute terminal commands, mainly when the restriction to the `terminado` has already been applied (see #8)

 2. Using `chmod` blocks users from reading, writing, and executing files and folders in `/etc/jupyter/`. This folder must be remained for `administrator` and `root`

**Comment by TheFlightSimsOfficial** [comment]
The MySQL password storing at `/etc/jupyter` security is mentioned [here](https://github.com/TheFlightSims/research-labs/issues/11). However, we also will follow your recommendations.

**Comment by takineko-tfs** [comment]
Reviewed the folder `/etc/jupyter/` permission. 

The problem is solved.
